<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>


				<section class="textArea"> <p style="text-align: left;"><strong><span style="color: #008080;">＊捐款芳名錄搜尋方式：請直接點選芳名錄連結，進入後請按Ctrl+F開啟尋找，輸入您要查詢的名字按ENTER即可。</span></strong></p>
<p style="text-align: left;">&nbsp;</p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/10710.txt">107年10月捐款芳名錄(txt檔開啟)&nbsp;</a> &nbsp; &nbsp;&nbsp;<a href="https://www.tfb.org.tw/uploads/root/10711.txt">107年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10708.txt">107年08月捐款芳名錄(txt檔開啟)&nbsp;</a> &nbsp; &nbsp;&nbsp;<a href="https://www.tfb.org.tw/uploads/root/benefaction/10709.txt">107年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10706.txt">107年06月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="https://www.tfb.org.tw/uploads/root/benefaction/10707.txt">107年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10704.txt">107年04月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="https://www.tfb.org.tw/uploads/root/benefaction/10705.txt">107年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10702.txt">107年02月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="https://www.tfb.org.tw/uploads/root/benefaction/10703.txt">107年03月捐款芳名錄(txt檔開啟</a>)</p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10612.txt">106年12月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="https://www.tfb.org.tw/uploads/root/benefaction/10701.txt">107年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="https://www.tfb.org.tw/uploads/root/benefaction/10610.txt">106年10月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="https://www.tfb.org.tw/uploads/root/benefaction/10611.txt">106年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10608.txt">106年08月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="https://www.tfb.org.tw/uploads/root/benefaction/10609.txt">106年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10606.txt">106年06月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="http://www.tfb.org.tw/uploads/root/benefaction/10607.txt">106年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10604.txt">106年04月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10605.txt">106年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10602.txt">106年02月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10603.txt">106年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10512.TXT">105年12月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10601.TXT">106年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10510.TXT">105年10月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10511.TXT">105年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10508.TXT">105年08月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10509.TXT">105年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10506.TXT">105年06月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10507.TXT">105年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10504.TXT">105年04月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10505.TXT">105年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10502.TXT">105年02月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10503.TXT">105年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10412.txt">104年12月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10501.TXT">105年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10410.TXT">104年10月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10411.txt">104年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10408.TXT">104年08月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10409.TXT">104年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10406.TXT">104年06月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10407.TXT">104年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10404.TXT">104年04月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10405.TXT">104年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10402.TXT">104年02月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10403.TXT">104年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10312.TXT">103年12月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp; <a href="http://www.tfb.org.tw/uploads/root/benefaction/10401.TXT">104年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10310.TXT">103年10月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10311.TXT">103年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10308.TXT">103年08月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10309.TXT">103年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10306.TXT">103年06月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10307.TXT">103年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10304.TXT">103年04月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10305.TXT">103年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10302.TXT">103年02月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10303.TXT">103年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10212.TXT">102年12月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10301.TXT">103年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10210.txt">102年10月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10211.TXT">102年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10208.TXT">102年08月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10209.TXT">102年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10206.TXT">102年06月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10207.TXT">102年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10204.TXT">102年04月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10205.TXT">102年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10202.TXT">102年02月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10203.TXT">102年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10112.TXT">101年12月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10201.TXT">102年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10110.TXT">101年10月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10111.TXT">101年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10108.TXT">101年08月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10109.TXT">101年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10106.txt">101年06月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10107.TXT">101年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10104.TXT">101年04月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10105.TXT">101年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10102.TXT">101年02月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10103.TXT">101年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10012.TXT">100年12月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10101.TXT">101年01月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10010.TXT">100年10月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10011.TXT">100年11月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10008.TXT">100年08月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10009.TXT">100年09月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10006.TXT">100年06月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10007.TXT">100年07月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10004.TXT">100年04月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10005.TXT">100年05月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10002.TXT">100年02月捐款芳名錄(txt檔開啟)</a> &nbsp; &nbsp; &nbsp;<a href="http://www.tfb.org.tw/uploads/root/benefaction/10003.TXT">100年03月捐款芳名錄(txt檔開啟)</a></p>
<p style="text-align: left;"><a href="http://www.tfb.org.tw/uploads/root/benefaction/10001.TXT">100年01月捐款芳名錄(txt檔開啟)</a>&nbsp; &nbsp; &nbsp;&nbsp;</p> </section>
